# Generated by Django 5.2.7 on 2026-02-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
